In [1]:
import numpy 
X = numpy.array([
    [12,7,3],
    [4 ,5,6],
    [7 ,8,9]
])

Y = numpy.array([
    [5,8,1],
    [6,7,3],
    [4,5,9]
])

In [3]:
numpy.sqrt(X ** 2 - Y ** 2)

array([[10.90871211,         nan,  2.82842712],
       [        nan,         nan,  5.19615242],
       [ 5.74456265,  6.244998  ,  0.        ]])

In [3]:
import numpy as np
frame1=np.zeros((64,64))

frame1


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:

# Python program to explain cv2.cvtColor() method  
   
# importing cv2  
import cv2  
   
# path  
path = r'/home/pratt3000/Pictures/Camera Roll/1.jpg'
   
# Reading an image in default mode 
src = cv2.imread(path)
frame = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
frame = cv2.resize(frame, dsize=(64, 64), interpolation=cv2.INTER_CUBIC)
frame

array([[ 86,  89,  84, ..., 175, 168, 171],
       [ 89,  88,  85, ..., 171, 169, 174],
       [ 91,  86,  79, ..., 177, 176, 172],
       ...,
       [ 65, 126, 123, ...,  78,  98,  99],
       [ 61, 116, 140, ..., 108,  95, 102],
       [ 89,  51, 121, ..., 100,  93, 110]], dtype=uint8)

In [15]:
frame1 = frame

p=cv2.absdiff(frame1, frame)
p

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [7]:
import config

from imageai.Detection import ObjectDetection
import os
import cv2
import numpy as np

from keras.models import Sequential
from keras.callbacks import Callback
from keras.layers import Conv2D, MaxPooling2D, Dropout, Dense, Flatten, UpSampling2D
from keras import backend as K

import random
import glob
# import wandb
# from wandb.keras import WandbCallback
import subprocess
import os
from PIL import Image
import numpy as np
from matplotlib.pyplot import imshow, figure
from keras.layers import Lambda, Reshape, Permute, Input, add, Conv3D, GaussianNoise, concatenate
from keras.layers import ConvLSTM2D, BatchNormalization, TimeDistributed, Add
from keras.models import Model

c=4
FRAME_BATCH_SIZE=3
IMG_SIZE=64
inp = Input((FRAME_BATCH_SIZE,IMG_SIZE,IMG_SIZE,1))
permuted = Permute((2,3,4,1))(inp)
noise = GaussianNoise(0.1)(permuted)
x = Permute((4,1,2,3))(noise)
x =(ConvLSTM2D(filters=c, kernel_size=(3,3),padding='same',name='conv_lstm1', return_sequences=True))(x)

c1=(BatchNormalization())(x)
x = Dropout(0.2)(x)
x =(TimeDistributed(MaxPooling2D(pool_size=(2,2))))(c1)

x =(ConvLSTM2D(filters=2*c,kernel_size=(3,3),padding='same',name='conv_lstm2',return_sequences=True))(x)
c2=(BatchNormalization())(x)
x = Dropout(0.2)(x)

x =(TimeDistributed(MaxPooling2D(pool_size=(2,2))))(c2)
x =(ConvLSTM2D(filters=4*c,kernel_size=(3,3),padding='same',name='conv_lstm3',return_sequences=True))(x)

x =(TimeDistributed(UpSampling2D(size=(2, 2))))(x)
x =(ConvLSTM2D(filters=4*c,kernel_size=(3,3),padding='same',name='conv_lstm4',return_sequences=True))(x)
x =(BatchNormalization())(x)

x =(ConvLSTM2D(filters=2*c,kernel_size=(3,3),padding='same',name='conv_lstm5',return_sequences=True))(x)
x =(BatchNormalization())(x)
x = Add()([c2, x])
x = Dropout(0.2)(x)

x =(TimeDistributed(UpSampling2D(size=(2, 2))))(x)
x =(ConvLSTM2D(filters=c,kernel_size=(3,3),padding='same',name='conv_lstm6',return_sequences=False))(x)
x =(BatchNormalization())(x)

x = (Flatten())(x)
x = (Dense(units=50, activation='relu'))(x)

x = (Dense(units=2, activation='relu'))(x)

model=Model(inputs=[inp], outputs=[x])

model.summary()


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 3, 64, 64, 1) 0                                            
__________________________________________________________________________________________________
permute_1 (Permute)             (None, 64, 64, 1, 3) 0           input_1[0][0]                    
__________________________________________________________________________________________________
gaussian_noise_1 (GaussianNoise (None, 64, 64, 1, 3) 0           permute_1[0][0]                  
__________________________________________________________________________________________________
permute_2 (Permute)  