In [1]:
import numpy 
X = numpy.array([
    [12,7,3],
    [4 ,5,6],
    [7 ,8,9]
])

Y = numpy.array([
    [5,8,1],
    [6,7,3],
    [4,5,9]
])

In [3]:
numpy.sqrt(X ** 2 - Y ** 2)

array([[10.90871211,         nan,  2.82842712],
       [        nan,         nan,  5.19615242],
       [ 5.74456265,  6.244998  ,  0.        ]])

In [3]:
import numpy as np
frame1=np.zeros((64,64))

frame1


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:

# Python program to explain cv2.cvtColor() method  
   
# importing cv2  
import cv2  
   
# path  
path = r'/home/pratt3000/Pictures/Camera Roll/1.jpg'
   
# Reading an image in default mode 
src = cv2.imread(path)
frame = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
frame = cv2.resize(frame, dsize=(64, 64), interpolation=cv2.INTER_CUBIC)
frame

array([[ 86,  89,  84, ..., 175, 168, 171],
       [ 89,  88,  85, ..., 171, 169, 174],
       [ 91,  86,  79, ..., 177, 176, 172],
       ...,
       [ 65, 126, 123, ...,  78,  98,  99],
       [ 61, 116, 140, ..., 108,  95, 102],
       [ 89,  51, 121, ..., 100,  93, 110]], dtype=uint8)

In [15]:
frame1 = frame

p=cv2.absdiff(frame1, frame)
p

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)